name: "Eva Payne"
description: "Personal website of Eva Payne"

url: "evapayne.github.io"

gems: [jekyll-paginate]
paginate: 5
paginate_path: "blog/page:num"

permalink: pretty
highlighter: rouge
markdown: kramdown
kramdown: 
  parse_block_html: true
